[package]
name = "spldcrdchlscrp"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.35.0", features = ["full"] }
color-eyre = "0.6.3"
thiserror = "1.0.59"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
clap = { version = "4.5.4", features = ["derive"] }
reqwest = { version = "0.11.14", features = ["json"] }
serde-jsonlines = "0.5.0"
serde_json = "1.0.117"
chrono = "0.4.38"
async-recursion = "1.1.1"

[dev-dependencies]
tracing-test = "0.2.4"
